<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
  <meta name="author" content="GeeksLabs">
  <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
  <link rel="shortcut icon" href="img/favicon.png">

  <title>Email Campaign</title>

  <link href="public/css/bootstrap.min.css" rel="stylesheet">
  <link href="public/css/bootstrap-theme.css" rel="stylesheet">
  <link href="public/css/elegant-icons-style.css" rel="stylesheet" />
  <link href="public/css/font-awesome.min.css" rel="stylesheet" />

  <link href="public/css/style.css" rel="stylesheet">
  <link href="public/css/style-responsive.css" rel="stylesheet" />

</head>

<body>
  <!-- container section start -->
  <section id="container" class="">
    <!--header start-->

    <header class="header dark-bg">
   
      <a href="index.html" class="logo">Project<span class="lite">EmailCampaign</span></a>
      
    </header>
    <!--header end-->

    <!--main content start-->
    <section id="main-content-home">
      <section class="wrapper">
        <div class="row">
          <div class="col-lg-7">
            <img style="height: 600px" src='a6.svg'>
            <h1>About Us</h1>
            Project Email Campaign was created by Divyanshu Joshi and launched on 21/05/2020 under the initiative of
            ColoredCow the company from hills. The aim of the Project was to help individuals
            with a platform that can help them to start a mailing campaing.

            <p>Here, we believe there is a better way to do marketing. A more valuable, less invasive way where
              customers are earned rather than bought. We're obsessively passionate about it, and our mission is to help
              people achieve it. We focus on search engine optimization (SEO). It's one of the least understood and
              least transparent aspects of great marketing, and we see that as an opportunity: We're excited to simplify
              SEO for everyone through our software, education, and community.
              </px>
          </div>
          <div class="col-md-3
          ">

          </div>
          <div class="col-md-2" >
            <h2 style="margin-top:100px; color:red ">You Get</h2>
            <p>
              *A Subscriber Base.
            </p>

            <p>
              *Access to Campaign List.
            </p>
            <p>
              *Access to our Global Subscriber List.
            </p>
            <p>
              *For Free.
            </p>
            <a href="home&index">
              <h3 style="color:green">Join Us</h3>
            </a>
            <p>*You can Launch Email Campaigns.</p>
            <p>*Add/Remove Subscribers.</p>
            <p>*You create the subscriber base.</p>

            <a href="home&aboutus">
              <h3 style="color:blue">About Us</h3>
            </a>
          </div>
        </div>

      </section>

    </section>
    <!--main content end-->
  </section>
</body>

</html>