<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
  <meta name="author" content="GeeksLabs">
  <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
  <link rel="shortcut icon" href="img/favicon.png">

  <title>Email Campaign</title>

  <link href="public/css/bootstrap.min.css" rel="stylesheet">
  <link href="public/css/bootstrap-theme.css" rel="stylesheet">
  <link href="public/css/elegant-icons-style.css" rel="stylesheet" />
  <link href="public/css/font-awesome.min.css" rel="stylesheet" />
  <link href="public/css/style.css" rel="stylesheet">
  <link href="public/css/style-responsive.css" rel="stylesheet" />

  <style type="text/css">
       @media(max-width:767px){
            .image1 {
                display: block!important; 
            }
            .image2 {
                display: none !important; 
            }
        }
    </style>

</head>

<body>
  <!-- container section start -->
 


  <section id="container" class="">
    <!--header start-->

    <header class="header dark-bg">
    
      <a href="home&index" class="logo">Project<span class="lite">EmailCampaign</span></a>
    
    </header>
    <!--header end-->

    <!--main content start-->
    <section id="main-content-home">
      <section class="wrapper">
        <div class="row">
          <div class="col-lg-7 image1">
            
            <img src="a5.svg" alt="img1" style="height: 700px;margin-top:50px;margin-left: 100px;display: block;" class="image2"> 
          </div>
          <div class="col-md-3
          ">
            <div id='loginDiv'>
              <?php include VIEW.'home/login.phtml' ?>
            </div>
            <div id='registerDiv'>
              <?php include VIEW."home/register.phtml";?>
            </div>
          </div>
          <div class="col-md-2 ">
            <h2 style="margin-top:100px ; color:red ">Email Marketing</h2>
            <p>
              We Are :
            </p>

            <p>
              *Best At Email Marketing.
            </p>
            <p>
              *Opensource.
            </p>
            <p>
              *Completely Free.
            </p>
            <a href="home&index">
              <h3 style="color:green">Join Us</h3>
            </a>
            <p>*You Can Launch Email Campaigns.</p>
            <p>*Add/Remove Subscribers.</p>
            <p>*You Create The Subscriber Base.</p>
            <a href="home&aboutus">
              <h3 style="color:blue">About Us</h3>
            </a>
          </div>
        </div>

      </section>

    </section>
    <!--main content end-->

  </section>
  <!-- container section end -->
  <!-- javascripts -->
  <script src="public/js/jquery.js"></script>
  <script src="public/js/bootstrap.min.js"></script>
  <!-- nice scroll -->
  <script src="public/js/jquery.scrollTo.min.js"></script>
  <script src="public/js/jquery.nicescroll.js" type="text/javascript"></script>
  <!--custome script for all page-->
  <script src="public/js/scripts.js"></script>


  <script>
    var x = document.getElementById("loginDiv");
    var y = document.getElementById("registerDiv");
    x.style.display = "none";
    y.style.display = "block";


    function myLogin() {
      var x = document.getElementById("loginDiv");
      var y = document.getElementById("registerDiv");
      if (x.style.display === "none") {
        x.style.display = "block";
        y.style.display = "none";

      } else {
        x.style.display = "none";
        y.style.display = "block";

      }
    }

  </script>


</body>

</html>