<div class='container' style="margin-top : 100px">
    <div class="row justify-content-center">
        <div class="col-md-6 col-offset-3" align="center">

            

                <form action='home&register' method='post' align='center'>
                    <h1 align='centre'>SignUp</h1>
                    <br>
                    <input placeholder="First Name*" type="text" name="firstname" class="form-control" required><br><br>
                    <input placeholder="Last Name*" type="text" name="lastname" class="form-control" required><br><br>
                    <input placeholder="Email*" type="email" name="email" class="form-control" required><br><br>
                    <input placeholder="Password*" type="password" name="passkey" class="form-control" required><br><br>
                    <input placeholder="Confirm Password*" type="password" name="CPassKey" class="form-control" required><br><br>
                    <input type="submit" value="SignUp" name="register" class="btn btn-primary">
                    <br><br><div>Already have an account ?<a href='#' onclick="myLogin()"> SignIn</a> instead.</div>
                    <p class='text-monospace' style="color:red;"><?php if(isset($this->view_data['Error'])){echo $this->view_data['Error']; unset($this->view_data);}?></p>
                </form>
          


        </div>
    </div>
</div>