<?php session_start();
if (!isset($_SESSION['LoggedIn'])) {
    header("Location: home&index");
}
?>

<?php include ROOT.'public/header.php'; ?>
<?php include ROOT.'public/topnav.php'; ?>
<?php include ROOT.'public/sidenav.php'; ?>


<section id="main-content">
      <section class="wrapper">
        <div class="row">
          <div class="col-lg-12">
            <h3 class="page-header"><i class="fa fa fa-bars"></i> List of all Campaigns</h3>
            <a class="btn btn-primary "data-toggle="modal" href="#launchCampaign">
                Launch New Campaign  
            </a><br>
            <br>
            <ol class="breadcrumb">
              <li><i class="fa fa-home"></i><a href="index.html">Home</a></li>
              <li><i class="fa fa-bars"></i>Campaign List</li>
            </ol>
          </div>
        </div>



        <form class="form-inline" role="form" action="dash&getCampaignSearchResults" method="post">
                          <div class="form-group">
                            <input type="text" name="element" class="form-control round-input sm-input" placeholder="Search by subject or date of campaign">
                          </div>
                          
                          <button type="submit" class="btn btn-primary">Go</button>
                        </form>


        
       <!--Campaign List Starts Here-->
<br>
       <div class="row">
          <div class="col-lg-12">
            <section class="panel">
              <header class="panel-heading">
                All Data
              </header>

              <table class="table table-striped table-advance table-hover" id="main">
                <tbody>
                  <tr>
                    <th><i class="icon_profile"></i> Title</th>
                    <th><i class="icon_calendar"></i> Date </th>
                    <th><i class="fa fa-user"></i> Launched By</th>  
                    <th><i class="fa fa-times"></i> Remove</th>  
                  </tr>
                  <?php
        foreach ($this->view_data as $entity) {
            $id = $entity['camp_id'];
            echo "<tr id='".$id."'>";
            foreach ($entity as $key=>$element) {
                if ($key=="reg_date") {
                    $x = str_split($element, 10);
                    echo "<td>".$x[0]."</td>";
                } elseif ($key != "detail"&&$key != "camp_id") {
                    echo "<td>".$element."</td>";
                }
            }
            echo '<td><div class="btn-group"><a class="btn btn-green" onclick="myCamp()" href="dash&reLaunchCampaign?id='.$id.'"><i class="fa fa-times"></i></a>
            </div></td></tr>';
        }
        echo "</table>";
        ?> 
      </div>
      </div>
     
</script>
      <?php include VIEW.'dash/mailFormModal.phtml'; ?>
        </section>
    </section>

    <script
			  src="http://code.jquery.com/jquery-3.4.1.min.js"
			  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
              crossorigin="anonymous">
</script>
             
<script type="text/javascript">
    $(document).ready(function(){
        $("#launchCampaign").on('click', function(){
            var subject = $("#subject").val();
            var detail = $("#detail").val();
            
            

            $.ajax(
               {
                   url:'dash&launchCampaign',
                   method:"POST",
                   data:{
                       subject: subject ,
                       detail: detail,
                   },
                   success: function(response){
                   
                    if (response.indexOf('successfull')>=0)
                    $("#smessage").html("Launch Successfull");
                    else
                    $("#emessage").html("Some Error Occured");
                   },
                   dataType:'text'  
               }
           );
           
           
        });
    }
    );
    </script>

<?php include ROOT.'public/footer.php'; ?>