<div>

<form method=post action='mail&fire'>
<div class="form-group">
    <label>Subject</label>
    <input class="form-control form-control-lg" name = 'emailSubject' type="text" placeholder="Subject...">
    <label >Body</label>
    <textarea class="form-control" name='emailBody' id="exampleFormControlTextarea1" rows="3"></textarea>
    <input type="submit" value="Fire Mails" name="Send" class="btn btn-warning">  
</div>
</form>

</div>