<div class="modal fade" id="launchCampaign" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Launch New Campaign</h4>
      </div>
      <div class="modal-body">

        <!--Form For Filling Campaign Details -->

        <div class="row">
          <div class="col-lg-12">
            <section class="panel">
              <header class="panel-heading">
                Campaign Detail
              </header>
              <div class="panel-body">
                <div class="form">
                  <form class="form-validate form-horizontal" id="feedback_form" method="post" action="mail&fire">

                    <div class="form-group ">
                      <label for="cname" class="control-label col-lg-2">Subject <span class="required">*</span></label>
                      <div class="col-lg-10">
                        <input class="form-control" id="subject" name="emailSubject" minlength="5" type="text"
                          required />
                      </div>
                    </div>
                    <div class="form-group ">
                      <label for="ccomment" class="control-label col-lg-2">Body<span class="required">*</span></label>
                      <div class="col-lg-10">
                        <textarea class="form-control " id="ccomment" name="emailBody" required></textarea>
                      </div>
                    </div>
                    <div class="form-group ">

                      <div class="col-lg-10">
                        <input class="btn btn-primary" id="" name="launch" type="submit" />
                        <button data-dismiss="modal" class="btn btn-danger" type="button">Cancle</button>
                      </div>
                    </div>

                  </form>
                </div>

              </div>
            </section>
          </div>
        </div>
        <script src="public/js/form-validation-script.js"></script>
      </div>

    </div>
  </div>
</div>