<?php session_start();
if (!isset($_SESSION['LoggedIn'])) {
    header("Location: home&index");
}
?>
<?php include ROOT.'public/header.php'; ?>
<?php include ROOT.'public/topnav.php'; ?>
<?php include ROOT.'public/sidenav.php'; ?>

<section id="main-content">
      <section class="wrapper">
      <div class="row">
          <div class="col-lg-12">
            <h3 class="page-header"><i class="fa fa-laptop"></i> Dashboard</h3>
            <ol class="breadcrumb">
              <li><i class="fa fa-home"></i><a href="index.html">Home</a></li>
              <li><i class="fa fa-laptop"></i>Dashboard</li>
            </ol>
          </div>
        </div>

        <div class="row text-left" >
        <a data-toggle="modal" href="#launchCampaign">
        <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 text-right">
            <div class="info-box blue-bg">
              <i class="fa fa-paper-plane-o "></i>
              <div class="count">Launch a new Campaign</div><br/>
              <div class="title ">Campaign</div>
            </div>
          </div></a>
      
        </div>  
          <div class="row">
          <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
            <div class="info-box dark-bg">
              <i class="fa fa-user"></i>
              <div class="count"><?=$this->view_data["SubCount"]?></div>
              <div class="title">Subscribers</div>
            </div>
          </div>
          <!--/.col-->

          <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 ">
            <div class="info-box brown-bg ">
              <i class="fa fa-envelope"></i>
              <div class="count"><?=$this->view_data["CampCount"]?></div>
              <div class="title ">Campaigns</div>
            </div>
          </div>
       

          <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
            <div class="info-box green-bg">
            <i class="fa fa-square"></i>
              <div class="count">3.141</div>
              <div class="title">Use This Value of Pie</div>
            </div>
            
          </div>
          <!--/.col-->

        </div>


      </section>
    </section>
<!--Modal For LAunchiing Campaign -->

<?php include VIEW.'dash/mailFormModal.phtml'; ?>
<?php include ROOT.'public/footer.php'; ?>