

<?php include VIEW.'header.phtml' ?>

<div class="page-wrap d-flex flex-row align-items-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center">
                <span class="display-1 d-block">Error 404</span>
                <div class="mb-4 lead">The page you are looking for was not found.</div>
                <a href="home&index" class="btn btn-link">Back to Home</a>
                <?= "<br><strong>Error Detail :</strong><br> ".$this->view_data?>
            </div>
        </div>
    </div>
</div>


<?php include VIEW.'footer.phtml' ?>