<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
  <meta name="author" content="GeeksLabs">
  <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
  <link rel="shortcut icon" href="img/favicon.png">

  <title>Blank | Creative - Bootstrap 3 Responsive Admin Template</title>


  <link href="public/css/bootstrap.min.css" rel="stylesheet">

  <link href="public/css/bootstrap-theme.css" rel="stylesheet">

  <link href="public/css/elegant-icons-style.css" rel="stylesheet" />
  <link href="public/css/font-awesome.min.css" rel="stylesheet" />

  <link href="public/css/style.css" rel="stylesheet">
  <link href="public/css/style-responsive.css" rel="stylesheet" />


</head>

<body>
  <!-- container section start -->
  <section id="container" class="">
    <!--header start-->

    <header class="header dark-bg">
      <!--logo start-->
      <a href="home&index" class="logo">Project<span class="lite">EmailCampaign</span></a>
      <!--logo end-->
    </header>
    <!--header end-->

    <!--main content start-->
    <section id="main-content-home">
      <section class="wrapper">
        <div class="row text-center">
          <div class="col-md-3 "></div>
          <div class="col-md-6 align=center">
            <h1>Password Reset<h1>
                <form action="verification&updatePassword" method="post">
                  <input name='email' type="email" class="form-control" id="eml" placeholder="Enter Email"><br>
                  <input name='otp' type="text" class="form-control" id="otp" placeholder="Enter OTP"><br>
                  <input name='npass' type="password" class="form-control" id="newPass" placeholder="New Password"><br>
                  <input name='cpass' type="password" class="form-control" id="confirmPass"
                    placeholder="Confirm Password"><br>
                  <button type="submit" id='ret' class="btn btn-primary">Reset</button>
                </form>
          </div>
          <h1 style="color:green ; margin-top:700px "><?=$this->view_data['message']?> <h1>
              <h3><a href="home&index">Go back to home page </a></h3>
              <div class="col-md-3 ">
              </div>

      </section>

    </section>
    <!--main content end-->
  </section>
</body>

</html>