

<?php include VIEW.'header.phtml' ?>

<div class="page-wrap d-flex flex-row align-items-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center">
                <span class="display-1 d-block">Unknown Error</span>
                <div class="mb-4 lead">Something bad happened.</div>
                <a href="home&index" class="btn btn-link">Back to Home</a>
            </div>
        </div>
    </div>
</div>


<?php include VIEW.'footer.phtml' ?>